#!/usr/bin/env bash
set -Eeuo pipefail

ITB_SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ITB_UI_API_BASE=${ITB_UI_API_BASE:-http://localhost:9000/api}
ITB_USER_STATE_FILE=${ITB_USER_STATE_FILE:-"$ITB_SCRIPT_DIR/.itb-users.env"}
ITB_BOOTSTRAP_STATE_FILE=${ITB_BOOTSTRAP_STATE_FILE:-"$ITB_SCRIPT_DIR/.itb-bootstrap.env"}
ITB_UI_CONTAINER=${ITB_UI_CONTAINER:-itb-ui}
ITB_VERIFY_ACTIVE_SESSION=${ITB_VERIFY_ACTIVE_SESSION:-${ITB_CREATE_ACTIVE_SESSION:-true}}
ITB_SESSION_CATALOGUE=$(python3 "$ITB_SCRIPT_DIR/session_catalogue.py")
ITB_PROVIDED_ADMIN_PASSWORD=${ITB_ADMIN_PASSWORD:-}
ITB_PROVIDED_TEST_PASSWORD=${ITB_TEST_PASSWORD:-}
ITB_PROVIDED_TEST_USER_NAME=${ITB_TEST_USER_NAME:-}
ITB_PROVIDED_TEST_USERNAME=${ITB_TEST_USERNAME:-}
ITB_PROVIDED_TEST_ORGANISATION=${ITB_TEST_ORGANISATION:-}
ITB_TEST_USER_NAME=${ITB_TEST_USER_NAME:-CDA Test User}
ITB_TEST_USERNAME=${ITB_TEST_USERNAME:-cda-test@itb}
ITB_TEST_ORGANISATION=${ITB_TEST_ORGANISATION:-CDA-DK Example}
ITB_WORK_DIR=$(mktemp -d "${TMPDIR:-/tmp}/cda-dk-itb-user.XXXXXX")
ITB_RESPONSE_FILE="$ITB_WORK_DIR/response"

cleanup() {
    rm -rf -- "$ITB_WORK_DIR"
}
trap cleanup EXIT

report_error() {
    local ITB_EXIT_CODE=$?
    printf 'Test-user setup stopped unexpectedly at line %s (exit %s).\n' "${BASH_LINENO[0]}" "$ITB_EXIT_CODE" >&2
    exit "$ITB_EXIT_CODE"
}
trap report_error ERR

for ITB_COMMAND in curl jq openssl; do
    if ! command -v "$ITB_COMMAND" >/dev/null 2>&1; then
        printf 'Required command not found: %s\n' "$ITB_COMMAND" >&2
        exit 1
    fi
done

if [[ -f "$ITB_USER_STATE_FILE" ]]; then
    # Generated by save_user_state below and deliberately excluded from Git.
    # shellcheck source=/dev/null
    source "$ITB_USER_STATE_FILE"
fi
if [[ -f "$ITB_BOOTSTRAP_STATE_FILE" ]]; then
    # Generated by setup-itb.sh and containing API identifiers and session IDs.
    # shellcheck source=/dev/null
    source "$ITB_BOOTSTRAP_STATE_FILE"
fi
if [[ -n "$ITB_PROVIDED_ADMIN_PASSWORD" ]]; then
    ITB_ADMIN_PASSWORD=$ITB_PROVIDED_ADMIN_PASSWORD
fi
if [[ -n "$ITB_PROVIDED_TEST_PASSWORD" ]]; then
    ITB_TEST_PASSWORD=$ITB_PROVIDED_TEST_PASSWORD
fi
if [[ -n "$ITB_PROVIDED_TEST_USER_NAME" ]]; then
    ITB_TEST_USER_NAME=$ITB_PROVIDED_TEST_USER_NAME
fi
if [[ -n "$ITB_PROVIDED_TEST_USERNAME" ]]; then
    ITB_TEST_USERNAME=$ITB_PROVIDED_TEST_USERNAME
fi
if [[ -n "$ITB_PROVIDED_TEST_ORGANISATION" ]]; then
    ITB_TEST_ORGANISATION=$ITB_PROVIDED_TEST_ORGANISATION
fi

ITB_ADMIN_USERNAME=${ITB_ADMIN_USERNAME:-admin@itb}
ITB_ADMIN_PASSWORD=${ITB_ADMIN_PASSWORD:-}
ITB_TEST_PASSWORD=${ITB_TEST_PASSWORD:-}

save_user_state() {
    umask 077
    {
        printf 'ITB_ADMIN_USERNAME=%q\n' "$ITB_ADMIN_USERNAME"
        printf 'ITB_ADMIN_PASSWORD=%q\n' "$ITB_ADMIN_PASSWORD"
        printf 'ITB_TEST_USER_NAME=%q\n' "$ITB_TEST_USER_NAME"
        printf 'ITB_TEST_USERNAME=%q\n' "$ITB_TEST_USERNAME"
        printf 'ITB_TEST_PASSWORD=%q\n' "$ITB_TEST_PASSWORD"
        printf 'ITB_TEST_ORGANISATION=%q\n' "$ITB_TEST_ORGANISATION"
    } > "$ITB_USER_STATE_FILE"
    chmod 600 "$ITB_USER_STATE_FILE"
}

login() {
    local ITB_USERNAME=$1
    local ITB_PASSWORD=$2
    local ITB_STATUS

    ITB_STATUS=$(curl --silent --show-error --connect-timeout 10 --max-time 30 \
        --output "$ITB_RESPONSE_FILE" --write-out '%{http_code}' \
        --request POST \
        --header 'Accept: application/json' \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode "email=$ITB_USERNAME" \
        --data-urlencode "password=$ITB_PASSWORD" \
        "$ITB_UI_API_BASE/oauth/access_token")
    [[ "$ITB_STATUS" =~ ^2[0-9][0-9]$ ]] || return 1
    ITB_ACCESS_TOKEN=$(jq -r '.access_token // empty' "$ITB_RESPONSE_FILE")
    [[ -n "$ITB_ACCESS_TOKEN" ]]
}

replace_one_time_password() {
    local ITB_USERNAME=$1
    local ITB_OLD_PASSWORD=$2
    local ITB_NEW_PASSWORD=$3
    local ITB_STATUS

    ITB_STATUS=$(curl --silent --show-error --connect-timeout 10 --max-time 30 \
        --output "$ITB_RESPONSE_FILE" --write-out '%{http_code}' \
        --request POST \
        --header 'Accept: application/json' \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode "email=$ITB_USERNAME" \
        --data-urlencode "old_password=$ITB_OLD_PASSWORD" \
        --data-urlencode "password=$ITB_NEW_PASSWORD" \
        "$ITB_UI_API_BASE/oauth/replacePassword")
    if [[ ! "$ITB_STATUS" =~ ^2[0-9][0-9]$ ]]; then
        printf 'Could not replace the one-time password for %s (HTTP %s).\n' "$ITB_USERNAME" "$ITB_STATUS" >&2
        jq . "$ITB_RESPONSE_FILE" >&2 2>/dev/null || true
        exit 1
    fi
    ITB_ACCESS_TOKEN=$(jq -er '.access_token' "$ITB_RESPONSE_FILE")
}

authenticated_get() {
    local ITB_PATH=$1
    local ITB_STATUS

    ITB_STATUS=$(curl --silent --show-error --connect-timeout 10 --max-time 30 \
        --output "$ITB_RESPONSE_FILE" --write-out '%{http_code}' \
        --header 'Accept: application/json' \
        --header 'X-Requested-With: XMLHttpRequest' \
        --header "Authorization: Bearer $ITB_ACCESS_TOKEN" \
        "$ITB_UI_API_BASE$ITB_PATH")
    if [[ ! "$ITB_STATUS" =~ ^2[0-9][0-9]$ ]]; then
        printf 'ITB UI API call failed: GET %s returned HTTP %s\n' "$ITB_PATH" "$ITB_STATUS" >&2
        jq . "$ITB_RESPONSE_FILE" >&2 2>/dev/null || true
        exit 1
    fi
}

authenticated_post_user() {
    local ITB_PATH=$1
    local ITB_PASSWORD=$2
    local ITB_STATUS

    ITB_STATUS=$(curl --silent --show-error --connect-timeout 10 --max-time 30 \
        --output "$ITB_RESPONSE_FILE" --write-out '%{http_code}' \
        --request POST \
        --header 'Accept: application/json' \
        --header 'X-Requested-With: XMLHttpRequest' \
        --header "Authorization: Bearer $ITB_ACCESS_TOKEN" \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode "user_name=$ITB_TEST_USER_NAME" \
        --data-urlencode "user_email=$ITB_TEST_USERNAME" \
        --data-urlencode "password=$ITB_PASSWORD" \
        --data-urlencode 'role_id=2' \
        "$ITB_UI_API_BASE$ITB_PATH")
    if [[ ! "$ITB_STATUS" =~ ^2[0-9][0-9]$ ]]; then
        printf 'ITB UI API call failed: POST %s returned HTTP %s\n' "$ITB_PATH" "$ITB_STATUS" >&2
        jq . "$ITB_RESPONSE_FILE" >&2 2>/dev/null || true
        exit 1
    fi
}

verify_test_user() {
    local ITB_STATUS ITB_SESSION_TO_VERIFY ITB_SLOT_INDEX ITB_SLOT_VARIABLE ITB_SLOT_LABEL

    if ! login "$ITB_TEST_USERNAME" "$ITB_TEST_PASSWORD"; then
        return 1
    fi
    authenticated_get /user/profile
    jq -e \
        --arg username "$ITB_TEST_USERNAME" \
        --arg organisation "$ITB_TEST_ORGANISATION" \
        '.email == $username and .role == 2 and .organization.sname == $organisation' \
        "$ITB_RESPONSE_FILE" >/dev/null || return 1
    ITB_TEST_ORGANISATION_ID=$(jq -er '.organization.id' "$ITB_RESPONSE_FILE")
    authenticated_get /vendor/organisation/hasTests
    jq -e '.hasTests == true' "$ITB_RESPONSE_FILE" >/dev/null || return 1

    if [[ "$ITB_VERIFY_ACTIVE_SESSION" == true ]]; then
        while IFS=$'\t' read -r ITB_SLOT_INDEX ITB_SLOT_VARIABLE ITB_SLOT_LABEL; do
            ITB_SESSION_TO_VERIFY=${!ITB_SLOT_VARIABLE:-}
            [[ -n "$ITB_SESSION_TO_VERIFY" ]] || continue
            ITB_STATUS=$(curl --silent --show-error --connect-timeout 10 --max-time 30 \
                --output "$ITB_RESPONSE_FILE" --write-out '%{http_code}' \
                --request POST \
                --header 'Accept: application/json' \
                --header 'X-Requested-With: XMLHttpRequest' \
                --header "Authorization: Bearer $ITB_ACCESS_TOKEN" \
                --header 'Content-Type: application/x-www-form-urlencoded' \
                --data-urlencode 'page=1' \
                --data-urlencode 'limit=10' \
                --data-urlencode "organization_id=$ITB_TEST_ORGANISATION_ID" \
                --data-urlencode "session_id=$ITB_SESSION_TO_VERIFY" \
                "$ITB_UI_API_BASE/reports/active")
            [[ "$ITB_STATUS" =~ ^2[0-9][0-9]$ ]] || return 1
            jq -e \
                --arg session "$ITB_SESSION_TO_VERIFY" \
                '[.. | objects | (.session? // .sessionId? // empty)] | any(. == $session)' \
                "$ITB_RESPONSE_FILE" >/dev/null || return 1
        done <<< "$ITB_SESSION_CATALOGUE"
    fi
}

print_verification_result() {
    if [[ "$ITB_VERIFY_ACTIVE_SESSION" == true && -n "${ITB_ACTIVE_SESSION_ID:-}" ]]; then
        printf 'Verified login, assigned tests and access to all configured active sessions for %s.\n' \
            "$ITB_TEST_USERNAME"
    else
        printf 'Verified login and assigned tests for %s.\n' "$ITB_TEST_USERNAME"
    fi
}

if [[ -n "$ITB_TEST_PASSWORD" ]] && verify_test_user; then
    save_user_state
    print_verification_result
    printf 'Credentials: %s\n' "$ITB_USER_STATE_FILE"
    exit 0
fi

if [[ -n "$ITB_ADMIN_PASSWORD" ]] && login "$ITB_ADMIN_USERNAME" "$ITB_ADMIN_PASSWORD"; then
    printf 'Authenticated with the configured ITB administrator.\n'
else
    if ! command -v docker >/dev/null 2>&1; then
        printf '%s\n' 'Docker is required to recover the initial admin@itb password from the local ITB logs.' >&2
        printf '%s\n' 'Alternatively, set ITB_ADMIN_PASSWORD to the current administrator password.' >&2
        exit 1
    fi
    ITB_ADMIN_ONE_TIME_PASSWORD=$(docker logs "$ITB_UI_CONTAINER" 2>&1 | awk '
        /The one-time password for the default administrator account \[admin@itb\] is:/ { capture = 1; next }
        capture {
            gsub(/\r/, "")
            if (length($0) == 36 && $0 ~ /^[[:xdigit:]-]+$/) password = $0
        }
        END { print password }
    ')
    if [[ -z "$ITB_ADMIN_ONE_TIME_PASSWORD" ]]; then
        printf '%s\n' 'Could not authenticate the ITB administrator or recover its current one-time password.' >&2
        printf '%s\n' 'Set ITB_ADMIN_PASSWORD to the current admin@itb password and rerun this script.' >&2
        exit 1
    fi
    ITB_ADMIN_PASSWORD="ItbAdmin!$(openssl rand -hex 16)"
    replace_one_time_password "$ITB_ADMIN_USERNAME" "$ITB_ADMIN_ONE_TIME_PASSWORD" "$ITB_ADMIN_PASSWORD"
    save_user_state
    printf 'Activated the default ITB administrator account.\n'
fi

authenticated_get /organizations/all
ITB_ORGANISATION_ID=$(jq -er \
    --arg organisation "$ITB_TEST_ORGANISATION" \
    'first(.[] | select(.sname == $organisation) | .id)' \
    "$ITB_RESPONSE_FILE")

authenticated_get "/organizations/users?id=$ITB_ORGANISATION_ID&page=1&limit=100"
ITB_TEST_USER_ID=$(jq -r \
    --arg username "$ITB_TEST_USERNAME" \
    'first(.data[] | select(.email == $username) | .id) // empty' \
    "$ITB_RESPONSE_FILE")

ITB_TEST_ONE_TIME_PASSWORD="CdaInitial!$(openssl rand -hex 16)"
if [[ -z "$ITB_TEST_USER_ID" ]]; then
    authenticated_post_user "/organizations/$ITB_ORGANISATION_ID/users/create" "$ITB_TEST_ONE_TIME_PASSWORD"
    printf 'Created basic ITB user %s in %s.\n' "$ITB_TEST_USERNAME" "$ITB_TEST_ORGANISATION"
else
    authenticated_post_user "/users/$ITB_TEST_USER_ID" "$ITB_TEST_ONE_TIME_PASSWORD"
    printf 'Reset existing ITB user %s for reproducible local login.\n' "$ITB_TEST_USERNAME"
fi

ITB_TEST_PASSWORD=${ITB_TEST_PASSWORD:-"CdaTest!$(openssl rand -hex 16)"}
replace_one_time_password "$ITB_TEST_USERNAME" "$ITB_TEST_ONE_TIME_PASSWORD" "$ITB_TEST_PASSWORD"
save_user_state

if ! verify_test_user; then
    printf 'The test account was created but its login or assigned-test verification failed.\n' >&2
    exit 1
fi

print_verification_result
printf 'Credentials: %s\n' "$ITB_USER_STATE_FILE"
