#!/usr/bin/env bash
set -euo pipefail

ITB_SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ITB_API_BASE=${ITB_API_BASE:-http://localhost:9000/api/rest}
ITB_ENABLE_XDS=${ITB_ENABLE_XDS:-false}
ITB_XDS_CONNECTOR_WSDL=${ITB_XDS_CONNECTOR_WSDL:-http://xds-api:8080/processing?wsdl}
ITB_VALIDATOR_WSDL=${ITB_VALIDATOR_WSDL:-http://cda-validator:8080/api/cda-dk/validation?wsdl}
ITB_STATE_FILE=${ITB_STATE_FILE:-"$ITB_SCRIPT_DIR/.itb-bootstrap.env"}
ITB_RUN_EXAMPLE=${ITB_RUN_EXAMPLE:-true}
ITB_CREATE_ACTIVE_SESSION=${ITB_CREATE_ACTIVE_SESSION:-true}
# Start the updated manual test definition without cancelling an older session.
ITB_FORCE_NEW_SESSION=${ITB_FORCE_NEW_SESSION:-false}
ITB_PROVIDED_COMMUNITY_API_KEY=${ITB_COMMUNITY_API_KEY:-}
ITB_PROVIDED_DOMAIN_API_KEY=${ITB_DOMAIN_API_KEY:-}
ITB_WORK_DIR=$(mktemp -d "${TMPDIR:-/tmp}/cda-dk-itb-setup.XXXXXX")
ITB_RESPONSE_FILE="$ITB_WORK_DIR/response"
ITB_TEST_SUITE_ARCHIVE="$ITB_WORK_DIR/cda-dk-validator-example.zip"

ITB_SETUP_CHECK_DEPLOYED=false

remove_setup_check() {
    local payload status
    payload=$(jq -cn --arg specification "$ITB_SPECIFICATION_API_KEY" \
        '{specification: $specification, testSuite: "cda-dk-setup-check"}')
    status=$(curl --silent --show-error --connect-timeout 10 --max-time 30 \
        --output "$ITB_WORK_DIR/cleanup-response" --write-out '%{http_code}' \
        --request POST --header "ITB_API_KEY: $ITB_COMMUNITY_API_KEY" \
        --header 'Content-Type: application/json' --data "$payload" \
        "$ITB_API_BASE/testsuite/undeploy") || return 1
    if [[ ! "$status" =~ ^2[0-9][0-9]$ ]]; then
        printf 'Could not remove temporary setup check (HTTP %s). Rerun setup to retry.\n' "$status" >&2
        return 1
    fi
    ITB_SETUP_CHECK_DEPLOYED=false
}

cleanup() {
    local status=$?
    if [[ "$ITB_SETUP_CHECK_DEPLOYED" == true ]]; then
        remove_setup_check || status=1
    fi
    rm -rf -- "$ITB_WORK_DIR"
    exit "$status"
}
trap cleanup EXIT

for ITB_COMMAND in curl jq zip python3; do
    if ! command -v "$ITB_COMMAND" >/dev/null 2>&1; then
        printf 'Required command not found: %s\n' "$ITB_COMMAND" >&2
        exit 1
    fi
done

ITB_SESSION_CATALOGUE=$(python3 "$ITB_SCRIPT_DIR/session_catalogue.py")

if [[ -f "$ITB_STATE_FILE" ]]; then
    # This file is generated by save_state below and contains only API identifiers.
    # shellcheck source=/dev/null
    source "$ITB_STATE_FILE"
fi

case "$ITB_ENABLE_XDS" in true|false) ;; *) printf 'ITB_ENABLE_XDS must be true or false.\n' >&2; exit 1 ;; esac
export ITB_ENABLE_XDS
# Existing sessions keep their old definitions. Only replace the saved active slots.
if [[ "${ITB_ACTIVE_FLOW:-upload}" != "$([[ "$ITB_ENABLE_XDS" == true ]] && printf xds || printf upload)" ]]; then
    ITB_FORCE_NEW_SESSION=true
fi

ITB_SAVED_COMMUNITY_API_KEY=${ITB_COMMUNITY_API_KEY:-}
if [[ -n "$ITB_PROVIDED_COMMUNITY_API_KEY" ]]; then
    if [[ -n "$ITB_SAVED_COMMUNITY_API_KEY" && "$ITB_PROVIDED_COMMUNITY_API_KEY" != "$ITB_SAVED_COMMUNITY_API_KEY" ]]; then
        unset ITB_SPECIFICATION_API_KEY ITB_ACTOR_API_KEY ITB_ORGANISATION_API_KEY
        unset ITB_SYSTEM_API_KEY ITB_TEST_SUITE_API_KEY
        while IFS=$'\t' read -r ITB_SLOT_INDEX ITB_SLOT_VARIABLE ITB_SLOT_LABEL; do
            unset "$ITB_SLOT_VARIABLE"
        done <<< "$ITB_SESSION_CATALOGUE"
        if [[ -z "$ITB_PROVIDED_DOMAIN_API_KEY" ]]; then
            unset ITB_DOMAIN_API_KEY
        fi
    fi
    ITB_COMMUNITY_API_KEY=$ITB_PROVIDED_COMMUNITY_API_KEY
fi
if [[ -n "$ITB_PROVIDED_DOMAIN_API_KEY" ]]; then
    ITB_DOMAIN_API_KEY=$ITB_PROVIDED_DOMAIN_API_KEY
fi

save_state() {
    local ITB_SAVED_INDEX ITB_SAVED_VARIABLE ITB_SAVED_LABEL
    umask 077
    {
        printf 'ITB_COMMUNITY_API_KEY=%q\n' "${ITB_COMMUNITY_API_KEY:-}"
        printf 'ITB_DOMAIN_API_KEY=%q\n' "${ITB_DOMAIN_API_KEY:-}"
        printf 'ITB_SPECIFICATION_API_KEY=%q\n' "${ITB_SPECIFICATION_API_KEY:-}"
        printf 'ITB_ACTOR_API_KEY=%q\n' "${ITB_ACTOR_API_KEY:-}"
        printf 'ITB_ORGANISATION_API_KEY=%q\n' "${ITB_ORGANISATION_API_KEY:-}"
        printf 'ITB_SYSTEM_API_KEY=%q\n' "${ITB_SYSTEM_API_KEY:-}"
        printf 'ITB_TEST_SUITE_API_KEY=%q\n' "${ITB_TEST_SUITE_API_KEY:-}"
        printf 'ITB_INTERACTIVE_TEST_CASE_API_KEY=%q\n' "${ITB_INTERACTIVE_TEST_CASE_API_KEY:-}"
        printf 'ITB_ACTIVE_FLOW=%q\n' "${ITB_ACTIVE_FLOW:-upload}"
        while IFS=$'\t' read -r ITB_SAVED_INDEX ITB_SAVED_VARIABLE ITB_SAVED_LABEL; do
            printf '%s=%q\n' "$ITB_SAVED_VARIABLE" "${!ITB_SAVED_VARIABLE:-}"
        done <<< "$ITB_SESSION_CATALOGUE"
    } > "$ITB_STATE_FILE"
    chmod 600 "$ITB_STATE_FILE"
}

api_call() {
    local ITB_METHOD=$1
    local ITB_PATH=$2
    local ITB_API_KEY=$3
    local ITB_PAYLOAD=${4:-}
    local ITB_STATUS
    local -a ITB_CURL_ARGS

    ITB_CURL_ARGS=(
        --silent
        --show-error
        --connect-timeout 10
        --max-time 180
        --output "$ITB_RESPONSE_FILE"
        --write-out '%{http_code}'
        --request "$ITB_METHOD"
        --header "Accept: application/json"
        --header "ITB_API_KEY: $ITB_API_KEY"
    )
    if [[ -n "$ITB_PAYLOAD" ]]; then
        ITB_CURL_ARGS+=(
            --header "Content-Type: application/json"
            --data "$ITB_PAYLOAD"
        )
    fi

    ITB_STATUS=$(curl "${ITB_CURL_ARGS[@]}" "$ITB_API_BASE$ITB_PATH")
    if [[ ! "$ITB_STATUS" =~ ^2[0-9][0-9]$ ]]; then
        printf 'ITB API call failed: %s %s returned HTTP %s\n' "$ITB_METHOD" "$ITB_PATH" "$ITB_STATUS" >&2
        if [[ -s "$ITB_RESPONSE_FILE" ]]; then
            jq . "$ITB_RESPONSE_FILE" 2>/dev/null || sed -n '1,120p' "$ITB_RESPONSE_FILE"
        fi
        exit 1
    fi
}

response_api_key() {
    jq -er '.apiKey' "$ITB_RESPONSE_FILE"
}

printf 'Using ITB REST API at %s\n' "$ITB_API_BASE"

if [[ -n "${ITB_COMMUNITY_API_KEY:-}" ]]; then
    if [[ -z "${ITB_DOMAIN_API_KEY:-}" ]]; then
        api_call GET /domain "$ITB_COMMUNITY_API_KEY"
        ITB_DOMAIN_API_KEY=$(jq -er '.apiKey' "$ITB_RESPONSE_FILE")
        save_state
    fi
    printf 'Using existing ITB community and domain.\n'
else
    if [[ -z "${ITB_MASTER_API_KEY:-}" ]]; then
        printf '%s\n' 'Set ITB_COMMUNITY_API_KEY for an existing domain, or ITB_MASTER_API_KEY to create a dedicated domain and community.' >&2
        exit 1
    fi

    if [[ -z "${ITB_DOMAIN_API_KEY:-}" ]]; then
        ITB_DOMAIN_PAYLOAD=$(jq -cn '{
            shortName: "CDA-DK",
            fullName: "Danish HL7 CDA",
            description: "Danish MedCom CDA validation examples and conformance tests."
        }')
        api_call PUT /domain "$ITB_MASTER_API_KEY" "$ITB_DOMAIN_PAYLOAD"
        ITB_DOMAIN_API_KEY=$(response_api_key)
        save_state
        printf 'Created ITB domain CDA-DK.\n'
    fi

    ITB_COMMUNITY_PAYLOAD=$(jq -cn --arg domain "$ITB_DOMAIN_API_KEY" '{
        shortName: "CDA-DK",
        fullName: "Danish HL7 CDA",
        description: "Local community for Danish MedCom CDA validator development.",
        domain: $domain
    }')
    api_call PUT /community "$ITB_MASTER_API_KEY" "$ITB_COMMUNITY_PAYLOAD"
    ITB_COMMUNITY_API_KEY=$(response_api_key)
    save_state
    printf 'Created ITB community CDA-DK.\n'
fi

if [[ -z "${ITB_SPECIFICATION_API_KEY:-}" ]]; then
    api_call GET "/domain/$ITB_DOMAIN_API_KEY/specifications?name=CDA-DK" "$ITB_COMMUNITY_API_KEY"
    ITB_SPECIFICATION_API_KEY=$(jq -r 'first(.[] | select(.shortName == "CDA-DK") | .apiKey) // empty' "$ITB_RESPONSE_FILE")
fi
if [[ -z "${ITB_SPECIFICATION_API_KEY:-}" ]]; then
    ITB_SPECIFICATION_PAYLOAD=$(jq -cn --arg domain "$ITB_DOMAIN_API_KEY" '{
        shortName: "CDA-DK",
        fullName: "Danish MedCom CDA documents",
        description: "Validation of Danish HL7 CDA documents against MedCom profiles.",
        domain: $domain
    }')
    api_call PUT /specification "$ITB_COMMUNITY_API_KEY" "$ITB_SPECIFICATION_PAYLOAD"
    ITB_SPECIFICATION_API_KEY=$(response_api_key)
    printf 'Created CDA-DK specification.\n'
else
    printf 'Using existing CDA-DK specification.\n'
fi
save_state

if [[ -z "${ITB_ACTOR_API_KEY:-}" ]]; then
    api_call GET "/specification/$ITB_SPECIFICATION_API_KEY/actors?name=CDA%20producer" "$ITB_COMMUNITY_API_KEY"
    ITB_ACTOR_API_KEY=$(jq -r 'first(.[] | select(.identifier == "cda-producer") | .apiKey) // empty' "$ITB_RESPONSE_FILE")
fi
if [[ -z "${ITB_ACTOR_API_KEY:-}" ]]; then
    ITB_ACTOR_PAYLOAD=$(jq -cn --arg specification "$ITB_SPECIFICATION_API_KEY" '{
        identifier: "cda-producer",
        name: "CDA producer",
        description: "A system producing Danish MedCom CDA documents.",
        default: true,
        specification: $specification
    }')
    api_call PUT /actor "$ITB_COMMUNITY_API_KEY" "$ITB_ACTOR_PAYLOAD"
    ITB_ACTOR_API_KEY=$(response_api_key)
    printf 'Created CDA producer actor.\n'
else
    printf 'Using existing CDA producer actor.\n'
fi
save_state

api_call GET "/configure/service?domain=$ITB_DOMAIN_API_KEY&key=cdaValidator" "$ITB_COMMUNITY_API_KEY"
ITB_SERVICE_COUNT=$(jq 'length' "$ITB_RESPONSE_FILE")
ITB_SERVICE_PAYLOAD=$(jq -cn \
    --arg address "$ITB_VALIDATOR_WSDL" \
    --arg domain "$ITB_DOMAIN_API_KEY" \
    '{
        key: "cdaValidator",
        address: $address,
        description: "Danish MedCom CDA validation service.",
        serviceType: "validation",
        apiType: "soap",
        identifier: "cda-dk-validator",
        version: "1.0.0",
        domain: $domain
    }')
if [[ "$ITB_SERVICE_COUNT" -eq 0 ]]; then
    api_call PUT /configure/service "$ITB_COMMUNITY_API_KEY" "$ITB_SERVICE_PAYLOAD"
    printf 'Registered cdaValidator test service.\n'
else
    api_call POST /configure/service "$ITB_COMMUNITY_API_KEY" "$ITB_SERVICE_PAYLOAD"
    printf 'Updated cdaValidator test service.\n'
fi

if [[ "$ITB_ENABLE_XDS" == true ]]; then
    api_call GET "/configure/service?domain=$ITB_DOMAIN_API_KEY&key=xdsConnector" "$ITB_COMMUNITY_API_KEY"
    ITB_XDS_SERVICE_COUNT=$(jq 'length' "$ITB_RESPONSE_FILE")
    ITB_XDS_PAYLOAD=$(jq -cn --arg address "$ITB_XDS_CONNECTOR_WSDL" --arg domain "$ITB_DOMAIN_API_KEY" '{
        key: "xdsConnector", address: $address, domain: $domain,
        description: "DDS CDA search and original-byte retrieval.", serviceType: "processing", apiType: "soap",
        identifier: "cda-dk-xds-connector", version: "1.0.0"
    }')
    if [[ "$ITB_XDS_SERVICE_COUNT" -eq 0 ]]; then
        api_call PUT /configure/service "$ITB_COMMUNITY_API_KEY" "$ITB_XDS_PAYLOAD"
    else
        api_call POST /configure/service "$ITB_COMMUNITY_API_KEY" "$ITB_XDS_PAYLOAD"
    fi
    printf 'Registered xdsConnector processing service.\n'
fi

"$ITB_SCRIPT_DIR/package-test-suite.sh" "$ITB_TEST_SUITE_ARCHIVE"
ITB_TEST_SUITE_BASE64=$(base64 < "$ITB_TEST_SUITE_ARCHIVE" | tr -d '\n')
ITB_DEPLOY_PAYLOAD=$(jq -cn \
    --arg specification "$ITB_SPECIFICATION_API_KEY" \
    --arg testSuite "$ITB_TEST_SUITE_BASE64" \
    '{
        specification: $specification,
        testSuite: $testSuite,
        ignoreWarnings: false,
        replaceTestHistory: false,
        updateSpecification: true,
        showIdentifiers: true
    }')
api_call POST /testsuite/deploy "$ITB_COMMUNITY_API_KEY" "$ITB_DEPLOY_PAYLOAD"
if [[ "$(jq -r '.completed' "$ITB_RESPONSE_FILE")" != true ]]; then
    printf 'The ITB rejected the example test suite:\n' >&2
    jq . "$ITB_RESPONSE_FILE" >&2
    exit 1
fi
ITB_TEST_SUITE_API_KEY=$(jq -er '.identifiers.testSuite' "$ITB_RESPONSE_FILE")
# Deployment identifiers follow the testcase order in test-suite/testSuite.xml.
ITB_DEPLOYED_TEST_CASE_KEYS=$(jq -ce '.identifiers.testCases' "$ITB_RESPONSE_FILE")
ITB_SLOT_COUNT=$(printf '%s\n' "$ITB_SESSION_CATALOGUE" | wc -l | tr -d ' ')
jq -e --argjson count "$ITB_SLOT_COUNT" 'length == $count and all(.[]; type == "string" and length > 0)' <<< "$ITB_DEPLOYED_TEST_CASE_KEYS" >/dev/null
while IFS=$'\t' read -r ITB_SLOT_INDEX ITB_SLOT_VARIABLE ITB_SLOT_LABEL; do
    if [[ "$ITB_SLOT_VARIABLE" == ITB_ACTIVE_SESSION_ID ]]; then
        ITB_INTERACTIVE_TEST_CASE_API_KEY=$(jq -er --argjson index "$ITB_SLOT_INDEX" '.[$index]' <<< "$ITB_DEPLOYED_TEST_CASE_KEYS")
    fi
done <<< "$ITB_SESSION_CATALOGUE"
save_state
printf 'Deployed CDA release test suite.\n'

if [[ -z "${ITB_ORGANISATION_API_KEY:-}" ]]; then
    api_call GET /organisation "$ITB_COMMUNITY_API_KEY"
    ITB_ORGANISATION_API_KEY=$(jq -r 'first(.[] | select(.shortName == "CDA-DK Example") | .apiKey) // empty' "$ITB_RESPONSE_FILE")
fi
if [[ -z "${ITB_ORGANISATION_API_KEY:-}" ]]; then
    ITB_ORGANISATION_PAYLOAD=$(jq -cn '{
        shortName: "CDA-DK Example",
        fullName: "CDA-DK Example Organisation"
    }')
    api_call PUT /organisation "$ITB_COMMUNITY_API_KEY" "$ITB_ORGANISATION_PAYLOAD"
    ITB_ORGANISATION_API_KEY=$(response_api_key)
    printf 'Created example organisation.\n'
else
    printf 'Using existing example organisation.\n'
fi
save_state

if [[ -z "${ITB_SYSTEM_API_KEY:-}" ]]; then
    api_call GET "/organisation/$ITB_ORGANISATION_API_KEY/systems" "$ITB_COMMUNITY_API_KEY"
    ITB_SYSTEM_API_KEY=$(jq -r 'first(.[] | select(.shortName == "CDA producer example") | .apiKey) // empty' "$ITB_RESPONSE_FILE")
fi
if [[ -z "${ITB_SYSTEM_API_KEY:-}" ]]; then
    ITB_SYSTEM_PAYLOAD=$(jq -cn --arg organisation "$ITB_ORGANISATION_API_KEY" '{
        shortName: "CDA producer example",
        fullName: "Example Danish CDA producer",
        description: "Demo system used to execute the validator example test.",
        version: "1.0.0",
        organisation: $organisation
    }')
    api_call PUT /system "$ITB_COMMUNITY_API_KEY" "$ITB_SYSTEM_PAYLOAD"
    ITB_SYSTEM_API_KEY=$(response_api_key)
    printf 'Created example system.\n'
else
    printf 'Using existing example system.\n'
fi
save_state

api_call GET "/conformance/$ITB_SYSTEM_API_KEY" "$ITB_ORGANISATION_API_KEY"
ITB_CONFORMANCE_COUNT=$(jq --arg actor "$ITB_ACTOR_API_KEY" '[.[] | select(.actor == $actor)] | length' "$ITB_RESPONSE_FILE")
if [[ "$ITB_CONFORMANCE_COUNT" -eq 0 ]]; then
    api_call PUT "/conformance/$ITB_SYSTEM_API_KEY/$ITB_ACTOR_API_KEY" "$ITB_ORGANISATION_API_KEY"
    printf 'Created example conformance statement.\n'
else
    printf 'Using existing example conformance statement.\n'
fi

if [[ "$ITB_RUN_EXAMPLE" == true ]]; then
    "$ITB_SCRIPT_DIR/package-test-suite.sh" "$ITB_WORK_DIR/setup-check.zip" setup-check
    ITB_SETUP_PAYLOAD=$(jq -cn \
        --arg specification "$ITB_SPECIFICATION_API_KEY" \
        --arg testSuite "$(base64 < "$ITB_WORK_DIR/setup-check.zip" | tr -d '\n')" \
        '{specification: $specification, testSuite: $testSuite, ignoreWarnings: false,
          replaceTestHistory: true, updateSpecification: false, showIdentifiers: true}')
    # Set before the call so cleanup also runs if deployment succeeds but its response is lost.
    ITB_SETUP_CHECK_DEPLOYED=true
    api_call POST /testsuite/deploy "$ITB_COMMUNITY_API_KEY" "$ITB_SETUP_PAYLOAD"
    if [[ "$(jq -r '.completed' "$ITB_RESPONSE_FILE")" != true ]]; then
        printf 'ITB rejected the temporary setup check.\n' >&2
        exit 1
    fi
    ITB_SETUP_TEST_CASE_API_KEY=$(jq -er '.identifiers.testCases[0]' "$ITB_RESPONSE_FILE")
    ITB_START_PAYLOAD=$(jq -cn \
        --arg system "$ITB_SYSTEM_API_KEY" \
        --arg actor "$ITB_ACTOR_API_KEY" \
        --arg testCase "$ITB_SETUP_TEST_CASE_API_KEY" \
        '{
            system: $system,
            actor: $actor,
            testCase: [$testCase],
            waitForCompletion: true,
            maximumWaitTime: 120000
        }')
    api_call POST /tests/start "$ITB_ORGANISATION_API_KEY" "$ITB_START_PAYLOAD"
    ITB_SESSION_ID=$(jq -er '.createdSessions[0].session' "$ITB_RESPONSE_FILE")
    ITB_STATUS_PAYLOAD=$(jq -cn --arg session "$ITB_SESSION_ID" '{
        session: [$session],
        withLogs: true,
        withReports: false
    }')
    api_call POST /tests/status "$ITB_ORGANISATION_API_KEY" "$ITB_STATUS_PAYLOAD"
    ITB_RESULT=$(jq -er '.sessions[0].result' "$ITB_RESPONSE_FILE")
    remove_setup_check
    printf 'Temporary connection check %s finished with %s.\n' "$ITB_SESSION_ID" "$ITB_RESULT"
    if [[ "$ITB_RESULT" != SUCCESS ]]; then
        jq -r '.sessions[0] | {result, message, logs}' "$ITB_RESPONSE_FILE" >&2
        exit 1
    fi
fi

# The database may retain pending sessions after the engine has lost them.
# Probe the local engine when available; remote/non-Docker setups can supply this timestamp.
ITB_ENGINE_STARTED_AT=${ITB_ENGINE_STARTED_AT:-}
if [[ -z "$ITB_ENGINE_STARTED_AT" && ( "$ITB_API_BASE" == http://localhost:* || "$ITB_API_BASE" == http://127.0.0.1:* ) ]] && command -v docker >/dev/null 2>&1; then
    # Docker Desktop's API can stall while ITB's HTTP API is still available.
    # Engine discovery is optional; do not let it block REST-based setup.
    ITB_ENGINE_STARTED_AT=$(python3 - "${ITB_ENGINE_CONTAINER:-itb-srv}" <<'PY'
import subprocess
import sys
try:
    result = subprocess.run(['docker', 'inspect', '--format', '{{.State.StartedAt}}', sys.argv[1]],
                            capture_output=True, text=True, timeout=10)
    if result.returncode == 0:
        print(result.stdout.strip())
except (OSError, subprocess.TimeoutExpired):
    pass
PY
    )
fi

ensure_active_session() {
    local ITB_SESSION_VARIABLE=$1
    local ITB_SESSION_TEST_CASE=$2
    local ITB_SESSION_LABEL=$3
    local ITB_SELECTED_SESSION_ID=${!ITB_SESSION_VARIABLE:-}
    local ITB_ACTIVE_SESSION_READY ITB_ACTIVE_STATUS_PAYLOAD ITB_INTERACTIVE_START_PAYLOAD ITB_ATTEMPT
    ITB_ACTIVE_SESSION_READY=false
    if [[ "$ITB_FORCE_NEW_SESSION" != true && -n "${ITB_SELECTED_SESSION_ID:-}" ]]; then
        ITB_ACTIVE_STATUS_PAYLOAD=$(jq -cn --arg session "$ITB_SELECTED_SESSION_ID" '{
            session: [$session],
            withLogs: false,
            withReports: false
        }')
        api_call POST /tests/status "$ITB_ORGANISATION_API_KEY" "$ITB_ACTIVE_STATUS_PAYLOAD"
        if jq -e '.sessions[0].result == "UNDEFINED" and (.sessions[0].endTime == null)' "$ITB_RESPONSE_FILE" >/dev/null; then
            if [[ -n "$ITB_ENGINE_STARTED_AT" ]] && ! python3 "$ITB_SCRIPT_DIR/session-survived-restart.py" "$ITB_ENGINE_STARTED_AT" < "$ITB_RESPONSE_FILE"; then
                printf 'Replacing %s session from before the engine restart; preserving its history.\n' "$ITB_SESSION_LABEL"
            else
                ITB_ACTIVE_SESSION_READY=true
                printf 'Using pending %s session %s.\n' "$ITB_SESSION_LABEL" "$ITB_SELECTED_SESSION_ID"
            fi
        fi
    fi

    if [[ "$ITB_ACTIVE_SESSION_READY" != true ]]; then
        ITB_INTERACTIVE_START_PAYLOAD=$(jq -cn \
            --arg system "$ITB_SYSTEM_API_KEY" \
            --arg actor "$ITB_ACTOR_API_KEY" \
            --arg testCase "$ITB_SESSION_TEST_CASE" \
            '{
                system: $system,
                actor: $actor,
                testCase: [$testCase],
                waitForCompletion: false
            }')
        api_call POST /tests/start "$ITB_ORGANISATION_API_KEY" "$ITB_INTERACTIVE_START_PAYLOAD"
        ITB_SELECTED_SESSION_ID=$(jq -er '.createdSessions[0].session' "$ITB_RESPONSE_FILE")
        printf -v "$ITB_SESSION_VARIABLE" '%s' "$ITB_SELECTED_SESSION_ID"
        save_state

        ITB_ACTIVE_STATUS_PAYLOAD=$(jq -cn --arg session "$ITB_SELECTED_SESSION_ID" '{
            session: [$session],
            withLogs: false,
            withReports: false
        }')
        ITB_ACTIVE_SESSION_READY=false
        for ITB_ATTEMPT in $(seq 1 30); do
            api_call POST /tests/status "$ITB_ORGANISATION_API_KEY" "$ITB_ACTIVE_STATUS_PAYLOAD"
            if jq -e '.sessions[0].result == "UNDEFINED" and (.sessions[0].endTime == null)' "$ITB_RESPONSE_FILE" >/dev/null; then
                ITB_ACTIVE_SESSION_READY=true
                break
            fi
            sleep 1
        done
        if [[ "$ITB_ACTIVE_SESSION_READY" != true ]]; then
            printf 'The user-driven session %s did not remain active.\n' "$ITB_SELECTED_SESSION_ID" >&2
            jq . "$ITB_RESPONSE_FILE" >&2
            exit 1
        fi
        printf 'Created pending %s session %s.\n' "$ITB_SESSION_LABEL" "$ITB_SELECTED_SESSION_ID"
    fi
}

if [[ "$ITB_CREATE_ACTIVE_SESSION" == true ]]; then
    while IFS=$'\t' read -r ITB_SLOT_INDEX ITB_SLOT_VARIABLE ITB_SLOT_LABEL; do
        ITB_SLOT_TEST_CASE=$(jq -er --argjson index "$ITB_SLOT_INDEX" '.[$index]' <<< "$ITB_DEPLOYED_TEST_CASE_KEYS")
        ensure_active_session "$ITB_SLOT_VARIABLE" "$ITB_SLOT_TEST_CASE" "$ITB_SLOT_LABEL"
    done <<< "$ITB_SESSION_CATALOGUE"
    ITB_ACTIVE_FLOW=$([[ "$ITB_ENABLE_XDS" == true ]] && printf xds || printf upload)
    save_state
fi

printf '\nITB setup is ready.\n'
printf 'UI: %s\n' "${ITB_UI_URL:-http://localhost:9000}"
printf 'Validator service parameter: $DOMAIN{cdaValidator}\n'
printf 'Local state: %s\n' "$ITB_STATE_FILE"
